const goalie = ["Sam"];
const defenders = ["Lisa", "Tom", "Jenny", "Jo"];
const midfielders = ["Jim", "Kai", "Ian", "Ava"];
const forwards = ["Kim", "Lucas"];
let goalieStr = "Goalie: ";
let defendersStr = "Defenders: ";
let midfieldersStr = "Midfielders: ";
let forwardsStr = "Forwards: ";
console.log(goalieStr + goalie[0]);
console.log(defendersStr + defenders);
console.log(midfieldersStr + midfielders);
console.log(forwards + forwardsStr);